version: '3.8'

services:
  # Backend сервис (NestJS)
  backend:
    image: node:22
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=dev.stan99.ru
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=example
      - DATABASE_NAME=practicum
    command: sh -c "npm ci && npm run start:dev"
    networks:
      - film_network

  # Frontend сервис (React + Vite)
  frontend:
    image: node:22
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_API_URL=http://localhost/api/afisha
      - VITE_CDN_URL=http://localhost/content/afisha
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend
    networks:
      - film_network

  # Nginx для проксирования
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - film_network

networks:
  film_network:
    driver: bridge

volumes:
  backend_node_modules:
  frontend_node_modules: